server:
  port: 80001

--- #################### 数据库相关配置 ####################

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/spring_boot_template?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456